### PR TITLE
Updated collections import to be compatible with Python 3.10 and newer

### LINKED ISSUE #154: Tools do not work in Python 3.10 due to deprecated import in collections module
# Summary

Using the NNEF tools (convert, visualize, etc.) with Python 3.10 and later fails with the following error:

```
ImportError: cannot import name 'Sequence' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

This is due to a change in the `collections` module:

> Remove deprecated aliases to [Collections Abstract Base Classes](https://docs.python.org/3/library/collections.abc.html#collections-abstract-base-classes) from the [collections](https://docs.python.org/3/library/collections.html#module-collections) module.

To reproduce this issue, install the tools locally and run the following with Python 3.8:

```sh
$ python3 -V
Python 3.10.4

$ python3 -m nnef_tools.convert -h
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/evan/.local/lib/python3.10/site-packages/nnef_tools-1.0-py3.10.egg/nnef_tools/convert.py", line 15, in <module>
  File "/home/evan/.local/lib/python3.10/site-packages/nnef_tools-1.0-py3.10.egg/nnef_tools/conversion/__init__.py", line 15, in <module>
  File "/home/evan/.local/lib/python3.10/site-packages/nnef_tools-1.0-py3.10.egg/nnef_tools/conversion/converter.py", line 17, in <module>
  File "/home/evan/.local/lib/python3.10/site-packages/nnef_tools-1.0-py3.10.egg/nnef_tools/model/__init__.py", line 15, in <module>
  File "/home/evan/.local/lib/python3.10/site-packages/nnef_tools-1.0-py3.10.egg/nnef_tools/model/graph.py", line 17, in <module>
ImportError: cannot import name 'Sequence' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

# Possible Fix

It should be possible to fix this by updating the import statement in `./nnef_tools/model/graph.py` from:

```python
from collections import Sequence
```

to

```python
from collections.abc import Sequence
```

I can submit a patch for this. Let me know if this is helpful.

### PR DESCRIPTION
**Pull request by evansmal**
Closes #154 

See issue #154 for more information. This PR updates collections import to be compatible with Python 3.10 and newer.

### CODE REVIEW

**Review by gyenesvi — APPROVED** [review]
Thanks for the update, indeed it is due.
